In [1]:
import numpy as np
import gym # pip intall gym
import random

In [2]:
env = gym.make('FrozenLake-v1', is_slippery = False)

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


Number of actions

In [3]:
env.action_space.n

4

Number of Observations Spaces

In [4]:
env.observation_space.n

16

In [5]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

qtable = np.zeros((state_space_size, action_space_size))
print("Q Table\n",qtable)

Q Table
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
total_episodes = 10000
learning_rate = 0.2
max_steps = 100
gamma = 0.99

epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
decay_rate = 0.001

In [7]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    for step in range(max_steps):

        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state,:]) # Exploit
        else:
            action = env.action_space.sample() # Explore

        new_state, reward, done, info = env.step(action)

        max_new_state = np.max(qtable[new_state,:])

        qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])
        total_rewards += reward

        state = new_state
        if done:
            break

    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)

print("Score:", str(sum(rewards)/total_episodes), " Reaches the goal this % of times")
print(qtable)

Score: 0.8755  Reaches the goal this % of times
[[9.41480149e-01 9.50990050e-01 9.32065348e-01 9.41480149e-01]
 [9.41480149e-01 0.00000000e+00 9.25718270e-01 9.28701466e-01]
 [4.69436649e-01 9.68772394e-01 1.44688840e-01 1.11792447e-01]
 [4.16914219e-01 0.00000000e+00 1.67864579e-02 7.74098631e-04]
 [9.50990050e-01 9.60596010e-01 0.00000000e+00 9.41480149e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.80100000e-01 0.00000000e+00 8.46213482e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.60596010e-01 0.00000000e+00 9.70299000e-01 9.50990050e-01]
 [9.60596010e-01 9.80100000e-01 9.80100000e-01 0.00000000e+00]
 [9.70299000e-01 9.90000000e-01 0.00000000e+00 9.70299000e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.78410150e-01 9.90000000e-01 9.63837064e-01]
 [9.80100000e-01 9.90000000e-01 1.00000000e+00 9.80100000e-01]
 [0.000

In [8]:
env.reset()

for episode in range(1):
    state = env.reset()
    step = 0
    done = False

    print("Episode:", episode+1)

    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        env.render()
        if done:

            print("Number of Steps:", step)
            break
        state = new_state

env.close()


Episode: 1


/usr/local/lib/python3.10/dist-packages/gym/core.py:49: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See here for more information: https://www.gymlibrary.ml/content/api/
  deprecation(


Number of Steps: 5
